import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import { WebSocketProvider } from '@/features/ws/WebSocketProvider'
import { cookies } from 'next/headers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const sessionId = cookieStore.get('auth')?.value || ''

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark max-h-screen antialiased`}
    >
      <body className="flex flex-col h-dvh" suppressHydrationWarning>
        <WebSocketProvider sessionId={sessionId}>{children}</WebSocketProvider>
      </body>
    </html>
  )
}
