import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/app/globals.css'
import Header from '@/ui/Header'
import ChatList from '@/features/chats/ChatsList'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="dark:bg-black ml-5  flex flex-col h-dvh">
      <Header />
      <main className="flex gap-12 flex-1 min-h-0">
        <ChatList />
        {children}
      </main>
    </div>
  )
}
