import type { Metadata } from 'next'
import '@/app/globals.css'
import Header from '@/ui/Header'
import ChatList from '@/features/chats/ChatsList'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="dark:bg-black ml-5  flex flex-col h-dvh">
      <Header />
      <main className="flex gap-12 flex-1 min-h-0">
        <ChatList />
        {children}
      </main>
    </div>
  )
}
